apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: aws-techzone
spec:
  data:
  - secretKey: awsAccessKeyId
    remoteRef:
      key: 4d18cfd7-84ee-dbb5-7567-cfef62391453
  - secretKey: awsSecretAccessKey
    remoteRef:
      key: 8a79517a-04f6-b772-cda6-bde1071d9005
  - secretKey: baseDomain
    remoteRef:
      key: f8b125d9-560d-e75a-3c9c-d61d04806999
  - secretKey: openshiftPullSecret
    remoteRef:
      key: 251a59d8-b3b1-2a96-767a-1412f781346f
  - secretKey: openshiftSSHPrivateKey
    remoteRef:
      key: 0d0f7777-332d-7233-58f0-6d0e7c428d8b
  - secretKey: openshiftSSHPublicKey
    remoteRef:
      key: a82957c4-8c6f-d39c-8ae6-0dda4b30c0ea
  refreshInterval: 24h
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: aws-techzone
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cluster.open-cluster-management.io/credentials: ""
          cluster.open-cluster-management.io/type: aws
      type: Opaque
      data:
        aws_access_key_id: "{{ .awsAccessKeyId | toString }}"
        aws_secret_access_key: "{{ .awsSecretAccessKey | toString }}"
        baseDomain: "{{ .baseDomain | toString }}"
        pullSecret: "{{ .openshiftPullSecret | toString }}"
        ssh-publickey: "{{ .openshiftSSHPublicKey | toString }}"
        ssh-privatekey: "{{ .openshiftSSHPrivateKey | toString }}"

